/* Auto-generated by genmsg_cpp for file /home/xps/ros_pkgs/siue-ros-pkg/siue_utils/serial_port_node/srv/SerialData.srv */
#ifndef SERIAL_PORT_NODE_SERVICE_SERIALDATA_H
#define SERIAL_PORT_NODE_SERVICE_SERIALDATA_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace serial_port_node
{
template <class ContainerAllocator>
struct SerialDataRequest_ : public ros::Message
{
  typedef SerialDataRequest_<ContainerAllocator> Type;

  SerialDataRequest_()
  : data()
  , length(0)
  {
  }

  SerialDataRequest_(const ContainerAllocator& _alloc)
  : data(_alloc)
  , length(0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  data;

  typedef int16_t _length_type;
  int16_t length;


private:
  static const char* __s_getDataType_() { return "serial_port_node/SerialDataRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "a9645de454fb3b94d33cdbf604ffc2ef"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "32dda19cd14525db231dce93a2ad9e7d"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string data\n\
int16 length\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, data);
    ros::serialization::serialize(stream, length);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, data);
    ros::serialization::deserialize(stream, length);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(data);
    size += ros::serialization::serializationLength(length);
    return size;
  }

  typedef boost::shared_ptr< ::serial_port_node::SerialDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_port_node::SerialDataRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct SerialDataRequest
typedef  ::serial_port_node::SerialDataRequest_<std::allocator<void> > SerialDataRequest;

typedef boost::shared_ptr< ::serial_port_node::SerialDataRequest> SerialDataRequestPtr;
typedef boost::shared_ptr< ::serial_port_node::SerialDataRequest const> SerialDataRequestConstPtr;


template <class ContainerAllocator>
struct SerialDataResponse_ : public ros::Message
{
  typedef SerialDataResponse_<ContainerAllocator> Type;

  SerialDataResponse_()
  : status(false)
  {
  }

  SerialDataResponse_(const ContainerAllocator& _alloc)
  : status(false)
  {
  }

  typedef uint8_t _status_type;
  uint8_t status;


private:
  static const char* __s_getDataType_() { return "serial_port_node/SerialDataResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "3a1255d4d998bd4d6585c64639b5ee9a"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "32dda19cd14525db231dce93a2ad9e7d"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool status\n\
\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, status);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, status);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(status);
    return size;
  }

  typedef boost::shared_ptr< ::serial_port_node::SerialDataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_port_node::SerialDataResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct SerialDataResponse
typedef  ::serial_port_node::SerialDataResponse_<std::allocator<void> > SerialDataResponse;

typedef boost::shared_ptr< ::serial_port_node::SerialDataResponse> SerialDataResponsePtr;
typedef boost::shared_ptr< ::serial_port_node::SerialDataResponse const> SerialDataResponseConstPtr;

struct SerialData
{

typedef SerialDataRequest Request;
typedef SerialDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SerialData
} // namespace serial_port_node

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::serial_port_node::SerialDataRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a9645de454fb3b94d33cdbf604ffc2ef";
  }

  static const char* value(const  ::serial_port_node::SerialDataRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa9645de454fb3b94ULL;
  static const uint64_t static_value2 = 0xd33cdbf604ffc2efULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_port_node::SerialDataRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serial_port_node/SerialDataRequest";
  }

  static const char* value(const  ::serial_port_node::SerialDataRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::serial_port_node::SerialDataRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string data\n\
int16 length\n\
\n\
";
  }

  static const char* value(const  ::serial_port_node::SerialDataRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::serial_port_node::SerialDataResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const  ::serial_port_node::SerialDataResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_port_node::SerialDataResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serial_port_node/SerialDataResponse";
  }

  static const char* value(const  ::serial_port_node::SerialDataResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::serial_port_node::SerialDataResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool status\n\
\n\
\n\
";
  }

  static const char* value(const  ::serial_port_node::SerialDataResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::serial_port_node::SerialDataResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::serial_port_node::SerialDataRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.data);
    stream.next(m.length);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SerialDataRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::serial_port_node::SerialDataResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.status);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SerialDataResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<serial_port_node::SerialData> {
  static const char* value() 
  {
    return "32dda19cd14525db231dce93a2ad9e7d";
  }

  static const char* value(const serial_port_node::SerialData&) { return value(); } 
};

template<>
struct DataType<serial_port_node::SerialData> {
  static const char* value() 
  {
    return "serial_port_node/SerialData";
  }

  static const char* value(const serial_port_node::SerialData&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<serial_port_node::SerialDataRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "32dda19cd14525db231dce93a2ad9e7d";
  }

  static const char* value(const serial_port_node::SerialDataRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<serial_port_node::SerialDataRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serial_port_node/SerialData";
  }

  static const char* value(const serial_port_node::SerialDataRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<serial_port_node::SerialDataResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "32dda19cd14525db231dce93a2ad9e7d";
  }

  static const char* value(const serial_port_node::SerialDataResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<serial_port_node::SerialDataResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "serial_port_node/SerialData";
  }

  static const char* value(const serial_port_node::SerialDataResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // SERIAL_PORT_NODE_SERVICE_SERIALDATA_H

